---
listen_addr: ":9999"
tor_addr: "localhost:9050"
timeout: "10s"
check_interval: "30s"
log_level: "error"
log_format: "fmt"
targets: []
#  - name: "website"
#    type: "http"
#    url: "http://7sk2kov2xwx6cbc32phynrifegg6pklmzs7luwcggtzrnlsolxxuyfyd.onion"
#  - name: "mumble"
#    type: "tcp"
#    url: "tcp://jntdndrgmfzgrnupgpm52xv2kwecq6mt4njyu2pzoenifsmiknxaasqd.onion:64738"
